# Generated by Django 5.2.15 on 2026-06-23 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentlar',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterModelTable(
            name='studentlar',
            table=None,
        ),
    ]
